# Posttest 7

<pre>Nama  : Alif Maulana Setyawan
NIM   : 2109106002
Kelas : A1 Informatika 2021

In [1]:
import tensorflow as tf

 ### 1. Tensor dengan `shape(5,5)` dengan `nilai random` yang disimpan dalam variable `random_tensor`.

In [2]:
random_tensor = tf.random.normal([5,5], seed=1)
random_tensor.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

### 2. Tensor dengan `shape(5,5)` dari sebuah `list` dengan nilai `bilangan prima` dalam variable `prime_tensor`.

In [3]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
                            71, 73, 79, 83, 89, 97, 101], shape=(5,5), dtype=tf.float32)

prime_tensor.numpy()

array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)

### 3. `Dimensi` dari kedua variable tersebut.

In [4]:
print('Dimensi dari random_tensor: ', random_tensor.shape)
print('Dimensi dari prime_tensor: ', prime_tensor.shape)

Dimensi dari random_tensor:  (5, 5)
Dimensi dari prime_tensor:  (5, 5)


In [5]:
dim_display_random = tf.constant(['random_tensor'], shape=[5,5])
dim_display_random.shape

print('Shape random_tensor:')
tf.shape(dim_display_random)

Shape random_tensor:


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

In [6]:
dim_display_prime = tf.constant(['prime_tensor'], shape=[5,5])
dim_display_prime.shape

print('Shape prime_tensor:')
tf.shape(dim_display_prime)

Shape prime_tensor:


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

### 4. Menampilkan hasil dari `perhitungan aritmetika` 2 variable tersebut (Menggunakan minimal 5 operator).

In [7]:
print("Penjumlahan:\n\n",
tf.add(random_tensor, prime_tensor).numpy())

Penjumlahan:

 [[  1.1886818   4.4845986   5.0653296   4.557296   11.099248 ]
 [ 13.591225   17.592823   16.877071   22.277103   28.94373  ]
 [ 31.643545   36.735676   42.856632   43.56784    46.617165 ]
 [ 51.514656   60.261772   60.974693   70.73537    74.532814 ]
 [ 77.25702    82.5621     88.43399    97.32067   102.13283  ]]


In [8]:
print("Pengurangan:\n\n", 
tf.subtract(random_tensor, prime_tensor).numpy())

Pengurangan:

 [[ -2.8113182  -1.5154012  -4.9346704  -9.442704  -10.900752 ]
 [-12.408775  -16.407177  -21.122929  -23.722897  -29.05627  ]
 [-30.356455  -37.264324  -39.143368  -42.43216   -47.382835 ]
 [-54.485344  -57.738228  -61.025307  -71.26463   -71.467186 ]
 [-80.74298   -83.4379    -89.56601   -96.67933   -99.86717  ]]


In [9]:
print("Perkalian:\n\n",
tf.multiply(random_tensor, prime_tensor).numpy())

Perkalian:

 [[  -1.6226364     4.4537964     0.32664686  -17.09893       1.0917324 ]
 [   7.685916     10.077991    -40.335663    -16.626637     -1.6318411 ]
 [  19.949888     -9.77999      76.12196      24.417194    -17.993286  ]
 [ -78.7232       74.444496     -1.5436709   -18.788708    111.89541   ]
 [-137.69519     -36.345116    -50.37489      31.10492     114.41593   ]]


In [10]:
print("Pembagian:\n\n",
tf.divide(random_tensor, prime_tensor).numpy())

Pembagian:

 [[-4.0565911e-01  4.9486625e-01  1.3065875e-02 -3.4895775e-01
   9.0225823e-03]
 [ 4.5478795e-02  3.4871940e-02 -1.1173314e-01 -3.1430315e-02
  -1.9403580e-03]
 [ 2.0759510e-02 -7.1438937e-03  4.5283735e-02  1.3205621e-02
  -8.1454450e-03]
 [-2.8025346e-02  2.1385951e-02 -4.1485377e-04 -3.7271788e-03
   2.0997450e-02]
 [-2.2063002e-02 -5.2758185e-03 -6.3596629e-03  3.3058687e-03
   1.1216149e-02]]


In [11]:
print("Pemangkatan:\n\n",
tf.pow(random_tensor, prime_tensor).numpy())

Pemangkatan:

 [[ 6.58237278e-01  3.27210546e+00  1.18998764e-06 -5.18914917e+02
   9.20362137e-12]
 [ 1.07839960e-03  1.37951167e-04 -1.62845650e+06 -5.73800469e-04
  -5.72948387e-37]
 [ 1.16397109e-06 -4.15966456e-22  1.04176673e+11  2.70254808e-11
  -2.52112615e-20]
 [-1.27886054e+09  9.07514625e+05 -0.00000000e+00 -0.00000000e+00
   3.47317018e+13]
 [-1.15356923e+19 -1.71214119e-30 -1.00310215e-22  0.00000000e+00
   2.95581156e+05]]


### 5. Menampilkan nilai `maksimum` dan `minimum` dari variable `random_tensor`.

#### a) Nilai Maksimum Perkolom

In [12]:
max_random_tensor1 = tf.argmax(random_tensor, axis = 0)
print("Lokasi indeks dari nilai maksimum : ", max_random_tensor1.numpy())

for i, x in enumerate(max_random_tensor1):
    print(f' Kolom: {i}  dengan nilai : {random_tensor[x, i]}')

Lokasi indeks dari nilai maksimum :  [2 0 2 2 3]
 Kolom: 0  dengan nilai : 0.6435447931289673
 Kolom: 1  dengan nilai : 1.4845987558364868
 Kolom: 2  dengan nilai : 1.856633186340332
 Kolom: 3  dengan nilai : 0.5678417086601257
 Kolom: 4  dengan nilai : 1.5328137874603271


#### b) Nilai Maksimum Perbaris

In [13]:
max_random_tensor2 = tf.argmax(random_tensor, axis = 1)
print("Lokasi indeks dari nilai maksimum : ", max_random_tensor2.numpy())

for i, x in enumerate(max_random_tensor2):
    print(f' Baris: {i}  dengan nilai : {random_tensor[x, i]}')

Lokasi indeks dari nilai maksimum :  [1 1 2 4 4]
 Baris: 0  dengan nilai : 0.5912243127822876
 Baris: 1  dengan nilai : 0.5928229689598083
 Baris: 2  dengan nilai : 1.856633186340332
 Baris: 3  dengan nilai : 0.3206692636013031
 Baris: 4  dengan nilai : 1.1328309774398804


#### c) Nilai Minimum Perkolom

In [14]:
min_random_tensor1 = tf.argmin(random_tensor, axis = 0)
print("Lokasi indeks dari nilai minimum : ", min_random_tensor1.numpy())

for i, x in enumerate(min_random_tensor1):
    print(f' Kolom: {i}  dengan nilai : {random_tensor[x, i]}')

Lokasi indeks dari nilai minimum :  [4 4 1 0 2]
 Kolom: 0  dengan nilai : -1.7429771423339844
 Kolom: 1  dengan nilai : -0.43789294362068176
 Kolom: 2  dengan nilai : -2.122929573059082
 Kolom: 3  dengan nilai : -2.442704200744629
 Kolom: 4  dengan nilai : -0.38283589482307434


#### d) Nilai Minimum Perbaris

In [15]:
min_random_tensor2 = tf.argmin(random_tensor, axis = 1)
print("Lokasi indeks dari nilai minimum : ", min_random_tensor2.numpy())

for i, x in enumerate(min_random_tensor2):
    print(f' Baris: {i}  dengan nilai : {random_tensor[x, i]}')

Lokasi indeks dari nilai minimum :  [3 2 4 0 0]
 Baris: 0  dengan nilai : -1.485343337059021
 Baris: 1  dengan nilai : -0.2643240690231323
 Baris: 2  dengan nilai : -0.5660099983215332
 Baris: 3  dengan nilai : -2.442704200744629
 Baris: 4  dengan nilai : 0.09924840182065964


### 6. Menampilkan `hasil` dari `penggabungan` variable `random_tensor` dengan `prime_tensor` `(concatenation)`

#### a) Concat axis 0

In [16]:
concat1 = tf.concat([random_tensor, prime_tensor], axis=0)
concat1.numpy()

array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
         1.0100000e+02]], dtype=float32)

#### b) Concat axis 1

In [17]:
concat2 = tf.concat([random_tensor, prime_tensor], axis=1)
concat2.numpy()

array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0100000e+02]], dtype=float32)

### 7. Menampilkan `hasil sorting` dari kedua variable di atas `(descending)`

#### a) Sorting Descending random_tensor

In [18]:
sort_random = tf.sort(random_tensor, direction="DESCENDING")
print(sort_random)

tf.Tensor(
[[ 1.4845988   0.0992484   0.06532937 -0.8113182  -2.4427042 ]
 [ 0.59282297  0.5912243  -0.05627038 -0.72289723 -2.1229296 ]
 [ 1.8566332   0.6435448   0.5678417  -0.26432407 -0.3828359 ]
 [ 1.5328138   1.2617711  -0.02530608 -0.2646297  -1.4853433 ]
 [ 1.132831    0.32066926 -0.43789294 -0.56601    -1.7429771 ]], shape=(5, 5), dtype=float32)


#### b) Sorting Descending prime_tensor

In [19]:
sort_prime = tf.sort(prime_tensor, direction="DESCENDING")
print(sort_prime)

tf.Tensor(
[[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73.  71.  61.  59.  53.]
 [101.  97.  89.  83.  79.]], shape=(5, 5), dtype=float32)
